/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedPricingRouteImport } from './routes/_protected/pricing'
import { Route as ProtectedHelloRouteImport } from './routes/_protected/hello'
import { Route as ProtectedFeaturesRouteImport } from './routes/_protected/features'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedDashboardSettingsRouteImport } from './routes/_protected/dashboard/settings'
import { Route as ProtectedDashboardIntegrationsRouteImport } from './routes/_protected/dashboard/integrations'
import { Route as ProtectedDashboardChatRouteImport } from './routes/_protected/dashboard/chat'
import { Route as ProtectedDashboardBillingRouteImport } from './routes/_protected/dashboard/billing'
import { Route as ProtectedDashboardAnalyticsRouteImport } from './routes/_protected/dashboard/analytics'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPricingRoute = ProtectedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelloRoute = ProtectedHelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeaturesRoute = ProtectedFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardSettingsRoute =
  ProtectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardIntegrationsRoute =
  ProtectedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardChatRoute = ProtectedDashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardBillingRoute =
  ProtectedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAnalyticsRoute =
  ProtectedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/features': typeof ProtectedFeaturesRoute
  '/hello': typeof ProtectedHelloRoute
  '/pricing': typeof ProtectedPricingRoute
  '/dashboard/analytics': typeof ProtectedDashboardAnalyticsRoute
  '/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/dashboard/chat': typeof ProtectedDashboardChatRoute
  '/dashboard/integrations': typeof ProtectedDashboardIntegrationsRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRoute
  '/features': typeof ProtectedFeaturesRoute
  '/hello': typeof ProtectedHelloRoute
  '/pricing': typeof ProtectedPricingRoute
  '/dashboard/analytics': typeof ProtectedDashboardAnalyticsRoute
  '/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/dashboard/chat': typeof ProtectedDashboardChatRoute
  '/dashboard/integrations': typeof ProtectedDashboardIntegrationsRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/features': typeof ProtectedFeaturesRoute
  '/_protected/hello': typeof ProtectedHelloRoute
  '/_protected/pricing': typeof ProtectedPricingRoute
  '/_protected/dashboard/analytics': typeof ProtectedDashboardAnalyticsRoute
  '/_protected/dashboard/billing': typeof ProtectedDashboardBillingRoute
  '/_protected/dashboard/chat': typeof ProtectedDashboardChatRoute
  '/_protected/dashboard/integrations': typeof ProtectedDashboardIntegrationsRoute
  '/_protected/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/features'
    | '/hello'
    | '/pricing'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/integrations'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/features'
    | '/hello'
    | '/pricing'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/chat'
    | '/dashboard/integrations'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/features'
    | '/_protected/hello'
    | '/_protected/pricing'
    | '/_protected/dashboard/analytics'
    | '/_protected/dashboard/billing'
    | '/_protected/dashboard/chat'
    | '/_protected/dashboard/integrations'
    | '/_protected/dashboard/settings'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/pricing': {
      id: '/_protected/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ProtectedPricingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hello': {
      id: '/_protected/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ProtectedHelloRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/features': {
      id: '/_protected/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof ProtectedFeaturesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/settings': {
      id: '/_protected/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ProtectedDashboardSettingsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/integrations': {
      id: '/_protected/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof ProtectedDashboardIntegrationsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/chat': {
      id: '/_protected/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof ProtectedDashboardChatRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/billing': {
      id: '/_protected/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof ProtectedDashboardBillingRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/analytics': {
      id: '/_protected/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof ProtectedDashboardAnalyticsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardAnalyticsRoute: typeof ProtectedDashboardAnalyticsRoute
  ProtectedDashboardBillingRoute: typeof ProtectedDashboardBillingRoute
  ProtectedDashboardChatRoute: typeof ProtectedDashboardChatRoute
  ProtectedDashboardIntegrationsRoute: typeof ProtectedDashboardIntegrationsRoute
  ProtectedDashboardSettingsRoute: typeof ProtectedDashboardSettingsRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardAnalyticsRoute: ProtectedDashboardAnalyticsRoute,
  ProtectedDashboardBillingRoute: ProtectedDashboardBillingRoute,
  ProtectedDashboardChatRoute: ProtectedDashboardChatRoute,
  ProtectedDashboardIntegrationsRoute: ProtectedDashboardIntegrationsRoute,
  ProtectedDashboardSettingsRoute: ProtectedDashboardSettingsRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedFeaturesRoute: typeof ProtectedFeaturesRoute
  ProtectedHelloRoute: typeof ProtectedHelloRoute
  ProtectedPricingRoute: typeof ProtectedPricingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedFeaturesRoute: ProtectedFeaturesRoute,
  ProtectedHelloRoute: ProtectedHelloRoute,
  ProtectedPricingRoute: ProtectedPricingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
